# Setup
title: Paradigm Shift by HTML5 UP
tagline: Your Website Tagline
url: https://avicndugu.github.io/bold-portfolio-jekyll/
paginate: 3
baseurl: "/bold-portfolio-jekyll/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Firstname secondname
  url: https://https://twitter.com/_ndugu
  email: authoremailaddress@gmail.com

# Custom vars
version: 3.0.0
